# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool: default

steps:

- task: NodeTool@0  
  inputs:  
    versionSpec: '12.x'  
  displayName: 'Install Node.js 12.x'  
- task: Npm@1  
  displayName: 'Install latest Angular CLI'  
  inputs:  
    command: custom  
    workingDir: ./
    verbose: false  
    customCommand: 'install @angular/cli@latest'  
- task: Npm@1  
  displayName: 'npm install'  
  inputs:  
    verbose: false  
  
- task: Npm@1  
  displayName: npm build 
  inputs:  
    command: custom  
    verbose: false  
    customCommand: 'run build --prod'  
  
- task: AzureRmWebAppDeployment@4
  displayName: Connet App Services
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(c9d4b655-c981-4696-93d6-bc06f9189051)'
    appType: 'webApp'
    WebAppName: 'DogNHomeClient'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'