# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: NodeTool@0  
  inputs:  
    versionSpec: '12.x'  
  displayName: 'Install Node.js 12.x'  
- task: Npm@1  
  displayName: 'Install latest Angular CLI'  
  inputs:  
    command: custom  
    verbose: false  
    customCommand: 'install @angular/cli@latest'  
- task: Npm@1  
  displayName: 'npm install'  
  inputs:  
    verbose: false  
  
- task: Npm@1  
  displayName: npm build 
  inputs:  
    command: custom  
    verbose: false  
    customCommand: 'run build --prod'  
  
- task: CopyPublishBuildArtifacts@1  
  displayName: 'Copy Publish Artifact: test'  
  inputs:  
    CopyRoot: dist  
    Contents: '**'  
    ArtifactName: test  
    ArtifactType: Container  
  
- task: DownloadPipelineArtifact@2  
  displayName: 'Download Pipeline Artifact'  
  inputs:  
    targetPath: ' $(Build.ArtifactStagingDirectory)/dist/AngularTest'  

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(c9d4b655-c981-4696-93d6-bc06f9189051)'
    appType: 'webApp'
    appName: 'DogNHomeClient'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'